services:
  - type: web
    name: mood-music-api
    env: node
    buildCommand: 'npm install'
    startCommand: 'node server/app.js'
    envVars:
      - key: SPOTIFY_CLIENT_ID
        fromSecret: SPOTIFY_CLIENT_ID
      - key: SPOTIFY_CLIENT_SECRET
        fromSecret: SPOTIFY_CLIENT_SECRET
      - key: PORT
        value: '5000' 