services:
  - type: web
    name: mood-music-api
    env: node
    buildCommand: 'npm install'
    startCommand: 'node server/app.js'
    envVars:
      - key: SPOTIFY_CLIENT_ID
        fromSecret: SPOTIFY_CLIENT_ID
      - key: SPOTIFY_CLIENT_SECRET
        fromSecret: SPOTIFY_CLIENT_SECRET
      - key: PORT
        value: '5000'

  - type: static
    name: mood-music-app
    buildCommand: 'cd client && chmod +x build.sh && ./build.sh'
    publishDir: 'client/build'
    envVars:
      - key: REACT_APP_API_URL
        sync: false
        value: 'https://mood-music-api.onrender.com' 