services:
  # Backend API Service
  - type: web
    name: mood-music-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node app.js
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: PORT
        value: 10000

  # Frontend Static Site
  - type: web
    name: mood-music-frontend
    env: static
    buildCommand: cd client && npm install && CI=false npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: mood-music-api
          type: web
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 